### ISSUE TITLE
Error using pop_rej_eyecontin Too many input arguments.

### ISSUE THREAD

**Issue by algrmur** [olafdimigen/eye-eeg#2]
I have been using EYE-EEG via the GUI for a while, since I hadn't fully standardised my analysis procedure and now I am looking to start scripting my preprocessing, so I took the details from EEG.history, but it looks like pop_rej_eyecontin causes an error when called as a function directly from a script (and not from the GUI). 

This is code taken from a successful preprocessing analysis that I then took to put into an automated script:
```

EEG = pop_loadbv(eeg_data_folder, eeg_data_filename);
EEG.setname='raw';
EEG = eeg_checkset(EEG);

% Import eyetracking information
EEG = pop_importeyetracker(EEG, fullfile(eeg_data_folder, fixed_et_data_filename),[sync_trigger_start sync_trigger_end] ,[2 3] ,{'L-GAZE-X' 'L-GAZE-Y'},0,1,0,1,4);
EEG.setname='raw_et-sync'; % added eye-tracking data & perform synchronisation
EEG = eeg_checkset(EEG);

% Reject bad eye-tracking data (keep the data, just mark it as bad)
EEG = pop_rej_eyecontin(EEG,[65 66] ,[1 1] ,[Inf Inf],100,2);
```
And I get the following error:

```
Error using pop_rej_eyecontin
Too many input arguments.
```

Since it works via the GUI and I remember Olaf implementing this specific change, I wonder if there is some edge case that needs to be changed elsewhere. Any info would be greatly appreciated as I really would like to avoid a GUI-style preprocessing of all the files I am about to acquire :)

**Comment by olafdimigen** [comment]
Hi algrmur,
thanks for the bug report - the number of function inputs was not correctly updated in all functions. Issue should be fixed now. 
Best, Olaf
